### ISSUE TITLE
XRDevice is obsolete error - unable to launch my program

### ISSUE THREAD

**Issue by burritosoftware** [I5UCC/MelonAutoLaunch#2]
Using A Dance of Fire and Ice, which is not a VR game. It seems that the use of XRDevice should be switched to prevent this.  
![image](https://user-images.githubusercontent.com/37681398/175862813-f404aa3c-ee8b-4f9a-9ba5-151a14fe12be.png)

**Comment by I5UCC** [comment]
I didnt think about that. 
I moved the used library to be an optional requirement (as it shouldve been) and created a new release.
Thanks for creating an issue!
